### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iygnohz** [NetEase/chatofpomelo#15]
我的环境：
$ npm -v
2.14.4
$ node -v
v4.1.1
OX X 10.10.5

> heapdump@0.2.9 install /Users/zhongyi/projects/test/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@4.1.1 | darwin | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/zhongyi/projects/test/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/zhongyi/.node-gyp/4.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/zhongyi/.node-gyp/4.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/zhongyi/projects/test/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
../src/heapdump.cc:158:52: error: no viable conversion from 'Local<v8::String>' to 'v8::ActivityControl *'
      isolate->GetHeapProfiler()->TakeHeapSnapshot(String::Empty(isolate)));
                                                   ^~~~~~~~~~~~~~~~~~~~~~
../src/heapdump.cc:36:25: note: expanded from macro 'COMPAT'
# define COMPAT(_, exp) exp
                        ^
/Users/zhongyi/.node-gyp/4.1.1/include/node/v8-profiler.h:487:24: note: passing argument to parameter 'control' here
      ActivityControl* control = NULL,
                       ^
1 error generated.
make: *** [Release/obj.target/heapdump/src/heapdump.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhongyi/projects/test/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

**Comment by boostbob** [comment]
我也遇到，这个错误和npm,node版本和分支有关~

**Comment by Z-K-PA** [comment]
npm install --ignore-scripts
